// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyekzxrxhwfwwiluiqja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZWt6eHJ4aHdmd3dpbHVpcWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NjYxMTEsImV4cCI6MjA2MzQ0MjExMX0.WKwx8mFIXOpUOZ-wqIJ-r0muybSHi488yE5TnErGENw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);